image: elixir:latest

stages:
  - test
  - build


before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

test:
  stage: test
  script:
    - MIX_ENV=test mix test
    
lint:
  stage: test
  script:
    - MIX_ENV=test mix credo --strict

build:
  stage: build
  script:
    - MIX_ENV=prod mix escript.build


